run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - staticcheck
    - unused
    - errcheck
    - dupl
    - goconst
    - gosec

linter-settings:
  goimports:
    local-prefixes: github.com/tuannguyensn2001/aurora-go
