version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enabled:
    - gofmt
    - goimports
    - staticcheck
    - unused
    - errcheck
    - dupl
    - goconst
    - gosec
  settings:
    goimports:
      local-prefixes: github.com/tuannguyensn2001/aurora-go
