version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - staticcheck
    - unused
    - errcheck
    - dupl
    - goconst
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/tuannguyensn2001/aurora-go
