// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	auroratype "github.com/tuannguyensn2001/aurora-go/auroratype"

	mock "github.com/stretchr/testify/mock"
)

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx
func (_m *MockFetcher) Fetch(ctx context.Context) (map[string]auroratype.Parameter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 map[string]auroratype.Parameter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]auroratype.Parameter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]auroratype.Parameter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]auroratype.Parameter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFetcher_Expecter) Fetch(ctx interface{}) *MockFetcher_Fetch_Call {
	return &MockFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx)}
}

func (_c *MockFetcher_Fetch_Call) Run(run func(ctx context.Context)) *MockFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFetcher_Fetch_Call) Return(_a0 map[string]auroratype.Parameter, _a1 error) *MockFetcher_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFetcher_Fetch_Call) RunAndReturn(run func(context.Context) (map[string]auroratype.Parameter, error)) *MockFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// IsStatic provides a mock function with no fields
func (_m *MockFetcher) IsStatic() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStatic")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFetcher_IsStatic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStatic'
type MockFetcher_IsStatic_Call struct {
	*mock.Call
}

// IsStatic is a helper method to define mock.On call
func (_e *MockFetcher_Expecter) IsStatic() *MockFetcher_IsStatic_Call {
	return &MockFetcher_IsStatic_Call{Call: _e.mock.On("IsStatic")}
}

func (_c *MockFetcher_IsStatic_Call) Run(run func()) *MockFetcher_IsStatic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetcher_IsStatic_Call) Return(_a0 bool) *MockFetcher_IsStatic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFetcher_IsStatic_Call) RunAndReturn(run func() bool) *MockFetcher_IsStatic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
