// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	auroratype "github.com/tuannguyensn2001/aurora-go/auroratype"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, parameterName
func (_m *MockStorage) Get(ctx context.Context, parameterName string) (auroratype.Parameter, error) {
	ret := _m.Called(ctx, parameterName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 auroratype.Parameter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (auroratype.Parameter, error)); ok {
		return rf(ctx, parameterName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) auroratype.Parameter); ok {
		r0 = rf(ctx, parameterName)
	} else {
		r0 = ret.Get(0).(auroratype.Parameter)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parameterName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - parameterName string
func (_e *MockStorage_Expecter) Get(ctx interface{}, parameterName interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, parameterName)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, parameterName string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(_a0 auroratype.Parameter, _a1 error) *MockStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(context.Context, string) (auroratype.Parameter, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, config
func (_m *MockStorage) Save(ctx context.Context, config map[string]auroratype.Parameter) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]auroratype.Parameter) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - config map[string]auroratype.Parameter
func (_e *MockStorage_Expecter) Save(ctx interface{}, config interface{}) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", ctx, config)}
}

func (_c *MockStorage_Save_Call) Run(run func(ctx context.Context, config map[string]auroratype.Parameter)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]auroratype.Parameter))
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(_a0 error) *MockStorage_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(context.Context, map[string]auroratype.Parameter) error) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
